import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import MyMenu from "@/components/my_menu";
import BottomNavbar from "@/components/nav-bar-gen";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider>
          <div className="flex flex-col h-screen">
            <div className="flex flex-1">
              {/* Sidebar: Allow it to resize properly */}
              <div className="w-auto flex-shrink-0">
                <AppSidebar />
              </div>

              {/* Main Content: Ensures it fully expands */}
              <div className="w-full flex-1 min-w-0 overflow-y-auto pb-20">
                <SidebarTrigger />
                <MyMenu />
                {children}
              </div>
            </div>

            {/* Bottom Navbar stays fixed at the bottom */}
            <BottomNavbar />
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
